module.exports = [
  {
    code: 'MODHME',
    name: 'HOME',
    display_name: 'Home',
    description: 'Application Home',
    route: '/home',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'res',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD001',
    name: 'RESTAURANTS',
    display_name: 'Restaurant',
    description: 'Restaurant and Branch Details.',
    route: '/restaurant',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'res',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD002',
    name: 'EMPLOYEES_LIST',
    display_name: 'Employees',
    description: 'Restaurant Employees list.',
    route: '/employees',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'emp',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD003',
    name: 'EMPLOYEE_PROFILE',
    display_name: 'Profile',
    description: 'Restaurant Employee Profile.',
    route: '/employees/profile',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'emp',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD004',
    name: 'EMPLOYEE_DETAILS',
    display_name: 'Profile',
    description: 'Restaurant Employee Profile.',
    route: '/employees/:id',
    mode: 'RESTAURANT',
    is_sub_module: 1,
    parent_module: 0,
    access_role: 'emp',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD005',
    name: 'EMPLOYEE_SIGNOUT',
    display_name: 'Signout',
    description: 'Restaurant Employee Profile.',
    route: '/signout',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 0,
    access_role: 'res',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD006',
    name: 'MENU_CATEGORIES',
    display_name: 'Menu Categories',
    description: 'Categories for the menu items.!',
    route: '/menu-categories',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'category',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD007',
    name: 'MENU_TYPES',
    display_name: 'Menu Types',
    description: 'Type of menu item.!',
    route: '/menu-types',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'menu',
    access_perm_level: 2,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
  {
    code: 'MOD008',
    name: 'MENU_ITEMS',
    display_name: 'Menu Items',
    description: 'list of menu items.!',
    route: '/menu-items',
    mode: 'RESTAURANT',
    is_sub_module: 0,
    parent_module: 1,
    access_role: 'menu',
    access_perm_level: 1,
    is_basic: 1,
    is_pro: 0,
    is_custom: 0,
  },
];
